// Generated by gencpp from file uuv_perception/color_id.msg
// DO NOT EDIT!


#ifndef UUV_PERCEPTION_MESSAGE_COLOR_ID_H
#define UUV_PERCEPTION_MESSAGE_COLOR_ID_H

#include <ros/service_traits.h>


#include <uuv_perception/color_idRequest.h>
#include <uuv_perception/color_idResponse.h>


namespace uuv_perception
{

struct color_id
{

typedef color_idRequest Request;
typedef color_idResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct color_id
} // namespace uuv_perception


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uuv_perception::color_id > {
  static const char* value()
  {
    return "9bf569996655985b2700639f8b6c0833";
  }

  static const char* value(const ::uuv_perception::color_id&) { return value(); }
};

template<>
struct DataType< ::uuv_perception::color_id > {
  static const char* value()
  {
    return "uuv_perception/color_id";
  }

  static const char* value(const ::uuv_perception::color_id&) { return value(); }
};


// service_traits::MD5Sum< ::uuv_perception::color_idRequest> should match
// service_traits::MD5Sum< ::uuv_perception::color_id >
template<>
struct MD5Sum< ::uuv_perception::color_idRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_perception::color_id >::value();
  }
  static const char* value(const ::uuv_perception::color_idRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_perception::color_idRequest> should match
// service_traits::DataType< ::uuv_perception::color_id >
template<>
struct DataType< ::uuv_perception::color_idRequest>
{
  static const char* value()
  {
    return DataType< ::uuv_perception::color_id >::value();
  }
  static const char* value(const ::uuv_perception::color_idRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uuv_perception::color_idResponse> should match
// service_traits::MD5Sum< ::uuv_perception::color_id >
template<>
struct MD5Sum< ::uuv_perception::color_idResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_perception::color_id >::value();
  }
  static const char* value(const ::uuv_perception::color_idResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_perception::color_idResponse> should match
// service_traits::DataType< ::uuv_perception::color_id >
template<>
struct DataType< ::uuv_perception::color_idResponse>
{
  static const char* value()
  {
    return DataType< ::uuv_perception::color_id >::value();
  }
  static const char* value(const ::uuv_perception::color_idResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UUV_PERCEPTION_MESSAGE_COLOR_ID_H
