// Generated by gencpp from file uuv_perception/color_idRequest.msg
// DO NOT EDIT!


#ifndef UUV_PERCEPTION_MESSAGE_COLOR_IDREQUEST_H
#define UUV_PERCEPTION_MESSAGE_COLOR_IDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace uuv_perception
{
template <class ContainerAllocator>
struct color_idRequest_
{
  typedef color_idRequest_<ContainerAllocator> Type;

  color_idRequest_()
    : imagen()
    , x(0)
    , y(0)
    , h(0)
    , w(0)  {
    }
  color_idRequest_(const ContainerAllocator& _alloc)
    : imagen(_alloc)
    , x(0)
    , y(0)
    , h(0)
    , w(0)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _imagen_type;
  _imagen_type imagen;

   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;

   typedef int64_t _h_type;
  _h_type h;

   typedef int64_t _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::uuv_perception::color_idRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uuv_perception::color_idRequest_<ContainerAllocator> const> ConstPtr;

}; // struct color_idRequest_

typedef ::uuv_perception::color_idRequest_<std::allocator<void> > color_idRequest;

typedef boost::shared_ptr< ::uuv_perception::color_idRequest > color_idRequestPtr;
typedef boost::shared_ptr< ::uuv_perception::color_idRequest const> color_idRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uuv_perception::color_idRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uuv_perception::color_idRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uuv_perception::color_idRequest_<ContainerAllocator1> & lhs, const ::uuv_perception::color_idRequest_<ContainerAllocator2> & rhs)
{
  return lhs.imagen == rhs.imagen &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.h == rhs.h &&
    lhs.w == rhs.w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uuv_perception::color_idRequest_<ContainerAllocator1> & lhs, const ::uuv_perception::color_idRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uuv_perception

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uuv_perception::color_idRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uuv_perception::color_idRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uuv_perception::color_idRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uuv_perception::color_idRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_perception::color_idRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_perception::color_idRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uuv_perception::color_idRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a7a6e73ededaa30b051c8c1863d8f3a";
  }

  static const char* value(const ::uuv_perception::color_idRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a7a6e73ededaa30ULL;
  static const uint64_t static_value2 = 0xb051c8c1863d8f3aULL;
};

template<class ContainerAllocator>
struct DataType< ::uuv_perception::color_idRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uuv_perception/color_idRequest";
  }

  static const char* value(const ::uuv_perception::color_idRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uuv_perception::color_idRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image imagen\n"
"int64 x\n"
"int64 y\n"
"int64 h\n"
"int64 w\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::uuv_perception::color_idRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uuv_perception::color_idRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.imagen);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.h);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct color_idRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uuv_perception::color_idRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uuv_perception::color_idRequest_<ContainerAllocator>& v)
  {
    s << indent << "imagen: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.imagen);
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
    s << indent << "h: ";
    Printer<int64_t>::stream(s, indent + "  ", v.h);
    s << indent << "w: ";
    Printer<int64_t>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UUV_PERCEPTION_MESSAGE_COLOR_IDREQUEST_H
